### ISSUE TITLE
Support for Kotlin classes/projects in pebvariable?

### ISSUE THREAD

**Issue by hpoul** [bjansen/pebble-intellij#34]
Should it be possible to use kotlin classes in a `@pebvariable` definition? I have a (standalone) kotlin project where i have been toying around with pebble templates, but I can't get @pebvariable to work. I played around quite a bit, and only found that the plugin uses `JavaLookupElementBuilder` - so I am not sure if this is actually supposed to work?

(I have tried a freemarker template, and there my @ftlvariable's are recognized.. so i guess my basic project setup should be right.. previously I did't have my templates in the 'resources' directory of the correct module, so it couldn't be resolved even in freemarker templates.)

**Comment by hpoul** [comment]
sorry, seems i figured it out after all.. I had to select "Kotlin" as "Project Language" in "Template Data Languages" ..

**Comment by bjansen** [comment]
Hi Herbert,

I'm trying to understand your project. You have a Kotlin project where you wrote Kotlin classes and maybe imported Java/Kotlin libraries. You also have a Pebble template, but I suppose those templates are not generating Kotlin code? You're most likely templating HTML or something like that, right?

In that case, you should not have to set Kotlin as the Template Data language, you should rather set it to HTML or whatever you are generating, in order to have the correct syntax highlighting in your templates.

I created a sample kotlin project with a sample class, and added a Pebble template with HTML content in it, and when I added a `@pebvariable`, my Kotlin class was correctly shown in the code completion popup.

I'm just trying to make sure that there is indeed no bug :)

**Comment by bjansen** [comment]
Note: you have to press ctrl+space twice to autocomplete types from the Kotlin stdlib and other libraries.

**Comment by hpoul** [comment]
@bjansen thanks for looking into this..
it seems that change to the `Project Language` was not really what fixed it.. (no idea why it looked like that made a difference)..

so i could at least reproduce 2 things more or less reliably..

1. When i'm outside the resource or class path no variables get resolved.. (I assume this is because i have two modules in my project `main` and `test`.. and when the files are outside of either of those modules they can't resolve the classpath? (I just tried it with basically a `gradle init` and selecting kotlin project with kotlin DSL - if this is something which is not supposed to be a requirement I could share this simple setup..
2. This is weird, maybe i still see some inconsistencies (it seems sometimes doing 'invalidate caches & restart' does make a difference.. it seems `abstract var` can't be resolved, but `abstract val` works.

```kotlin
package design.codeux.pebbletest

interface ExampleInterface {
    val foo: String
    var bar: String
}
```
<img width="750" alt="screenshot 2019-02-14 at 14 43 48" src="https://user-images.githubusercontent.com/313066/52790481-f5ca8b00-3066-11e9-99e6-ccc12ee1075f.png">

(`ii.getBar()` is resolved but `ii.bar` is not)

**Comment by bjansen** [comment]
1. I Don't think I did something specific regarding code completion in `@pebvariable` types, so I guess it's using the default IntelliJ completion strategy. That's why you have to press the shortcut twice. This means that the completion proposals will only contain declarations that are in the classpath of the module containing the template. If your template is outside of a module, then completion won't work correctly (probably just like in any other language).
2. I have to admit I haven't tried to use Kotlin declarations in Pebble templates. The plugin will try to list members of the corresponding class, and categorize them as fields, methods, getters/setters etc. The Pebble engine works in a similar way, it uses reflection on bytecode, which means it doesn't really care if the source code was written in Java or Kotlin. I'll have to check how `var bar` is translated in the resulting bytecode, maybe it's a regular getter and in that case there's probably something to fix in the plugin. Does the Pebble engin accept this template, or does it show an error as well on `ii.bar`?
