### ISSUE TITLE
Impossible to change indentation settings

### ISSUE THREAD

**Issue by grishka** [bjansen/pebble-intellij#48]
First of all, I despise using 4 spaces for indents. There's a special character for this purpose.

The problem is, the plugin insists I use 4 spaces in my templates, and when I click "configure indents for pebble", it doesn't offer me a choice. This is the window that comes up:
![Снимок экрана 2020-09-01 в 17 49 43](https://user-images.githubusercontent.com/1478258/91866813-95686200-ec7b-11ea-83ac-50b928002a38.png)

The built-in ones offer a checkbox to "use tab character":
![Снимок экрана 2020-09-01 в 17 51 15](https://user-images.githubusercontent.com/1478258/91867058-db252a80-ec7b-11ea-8b6a-bacb8eeec918.png)

I'm not asking you to implement something this advanced, but a similar checkbox would be nice.

**Comment by bjansen** [comment]
Hi,

> I despise using 4 spaces for indents

😆 

> the plugin insists I use 4 spaces in my templates

Are you talking about indentation *inside* Pebble tags (like `{% for ... %}`), or *around* tags?

I tested indentation on an HTML template (HTML indentation is configured to use tabs instead of spaces):
* when I press the <kbd>TAB</kbd>/<kbd>ENTER</kbd> key, it inserts spaces (incorrect behavior, like you are experiencing)
* but when I reformat the whole file, indents are converted to tabs (correct)

I'll try to fix this erratic behavior. Indents will then have to be configured for the template data language (e.g. HTML), not for the Pebble language itself (unless you want to configure indents inside `{% %}` tags).

**Comment by grishka** [comment]
> Are you talking about indentation inside Pebble tags (like {% for ... %}), or around tags?

Around, as in, at the beginning of each line.

**Comment by bjansen** [comment]
Hey, could you try this build and let me know if it improves your workflow?

[pebble-intellij.zip](https://github.com/bjansen/pebble-intellij/files/5184708/pebble-intellij.zip)

You'll have to [install a plugin from disk](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk).

The plugin should be using the correct indentation for the surrounding language parts.
