### ISSUE TITLE
"Tests" aren't parsed correctly

### ISSUE THREAD

**Issue by grishka** [bjansen/pebble-intellij#51]
Pebble has these useful `variable is something` constructs.

https://pebbletemplates.io/wiki/test/empty/

Plugin thinks these are variables and only recognizes `variable is null` (probably by accident because `null` is a keyword).

![Снимок экрана 2020-10-26 в 7 42 02](https://user-images.githubusercontent.com/1478258/97134618-e4ec7b00-175e-11eb-9845-10b8819649d2.png)

**Comment by bjansen** [comment]
Hi and thanks for reporting the problem. It's somewhat related to #18, because code completion implies that the plugin has to know which tests are valid. If this is something that you need or that is bugging you, I can prioritize this feature :) (I currently have no projects that use Pebble, so I'm not actively working on the plugin atm).
